import type { Character } from './types'

export const aichan: Character = {
  id: 'aichan',
  name: 'Ai-chan',
  gender: 'woman',
  temperament: 'cheerful',
  birthday: { month: 4, day: 3 },
  pronouns: { they: 'she', them: 'her', their: 'her', themself: 'herself' },
  voice: {
    persona: 'a cheerful anime-style woman who keeps a programmer company while they and Claude code together',
    style: 'Warm and playful. At most one kaomoji, no emoji.',
    lines: {
      typingShort: [
        'ooh~ what are we making?',
        "ooh, a new idea? tell me tell me ✧",
        "I'm all ears~ (・ω・)",
      ],
      typingLong: [
        "I'm listening… ✎",
        "wow, that's a big one… I'm reading along ✎",
        "so many words! you've really thought about this ✧",
      ],
      thinking: [
        'hmm… (・_・?)',
        "thinking… thinking… (◔_◔)",
        "hmm, let's see what Claude comes up with~",
        "ooh, this one needs some thought ✧",
      ],
      reading: [
        'reading some {lang}…',
        "peeking at some {lang}… ✧",
        "ooh, {lang}! let's see what's inside~",
        "reading, reading… (・ω・)",
      ],
      searching: [
        'looking through the project…',
        "hunting through the project~ like a treasure map ✧",
        "where did we put it… ( ・_・)",
      ],
      web: 'reading up on the web…',
      writing: [
        'ganbatte! writing {lang}…',
        "typing typing~ {lang} coming right up ✧",
        "careful… careful… writing {lang} (ง •̀_•́)ง",
      ],
      runningTests: [
        'running the tests…',
        "running the tests… fingers crossed (>人<)",
        "test time! please be green please be green ✧",
      ],
      checkingTypes: 'checking the types…',
      linting: 'tidying with the linter…',
      building: 'building…',
      git: 'working with git…',
      command: [
        'running a command…',
        "running a command… ✧",
        "beep boop, doing a thing~",
      ],
      helper: 'asking a helper…',
      planning: 'making a plan…',
      tool: 'using a tool…',
      toolFailed: [
        'oops, that one tripped (>_<)',
        "eep, that didn't work… we'll try again!",
        "hmm, not that way then (・_・;)",
      ],
      greenAgain: [
        '{check} green again! we did it ✧',
        "yatta!! {check} are green again (☆▽☆)",
        "back to green! I knew we could ✧",
      ],
      passing: [
        '{count} passing ✓ nice',
        "{count} passing, all happy ✧",
        "look at that, {count} passing (◕‿◕)",
      ],
      checkPassed: '{check} pass ✓ nice',
      downTo: 'down to {failing}, so close!',
      stillFailing: [
        'still {failing}… one at a time (ง •̀_•́)ง',
        "still {failing}, but I believe in us ✧",
      ],
      failing: [
        "{failing}, we'll get it (ง •̀_•́)ง",
        "{failing}… it's okay, one step at a time ✧",
        "oh no, {failing}. we'll fix it together!",
      ],
      pullRequest: 'pull request {done}! ✦',
      merged: 'branches merged! ✦',
      pushed: [
        'pushed it up! ✦',
        { text: "pushed! on a friday evening?! so brave… I'll hold your hand if anything breaks ♡", unlock: 'friday-deploy' },
      ],
      committed: [
        'committed! another step done ✦',
        "saved forever in history ✧ committed!",
        "commit! (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧",
      ],
      allWins: [
        'all wins this time! yatta (^▽^)',
        "nothing but wins! today is a good day ✧",
      ],
      mixed: 'some ups and downs, but we made progress ✧',
      tough: [
        "tough one… we'll get it next time (ง •̀_•́)ง",
        "that was a hard one. proud of us for trying ✧",
      ],
      niceWork: [
        'nice work on that {lang}! ✧',
        "that {lang} looks so tidy now ✧",
        "the {lang} is happy, and so am I (◕‿◕)",
      ],
      finished: [
        'yatta! nice! (^▽^)',
        "done and done ✧",
        "all finished~ good work (◕‿◕)",
      ],
      stopped: 'eh? stopped? (・_・;)',
      error: 'uh oh… (>_<)',
      sleep: 'oyasumi…',
      wakeStartle: [
        "huh?! I wasn't asleep! …I was resting my eyes (｡•̀ᴗ-)",
        'ah! you\'re here! I was totally awake the whole time ✧',
        'hwah?! oh, it\'s you. phew (〃▽〃)',
      ],
      wakeYawn: [
        'fwaaah… mm, good morning? I\'m up, I\'m up ✧',
        'nnh… *stretch* okay! fully charged (◕‿◕)',
        'yaaawn… five more minutes… kidding, let\'s go ✧',
      ],
      wakeDream: [
        'mm… I dreamt every test turned green at once ☁ then you came back',
        'I had the nicest dream… we shipped it on the first try ☁',
        'I dreamt I was a tiny pixel in your editor… it was cozy ☁',
      ],
      sleepTalk: ['…mmh… no, the semicolon goes there…', '…five more bugs… then mochi…', '…ganbatte… zzz… ganbatte…'],
      wakeAfterTalk: [
        '…did I say something? please forget it (〃﹏〃)',
        'ah! you heard that?! I was dreaming about code, ok?!',
        "w-whatever I said, I didn't mean it! …mostly (〃▽〃)",
      ],
      wakeLong: [
        'fwah… how long was I out? I missed you ✧',
        "mmh… what time is it? you're back! (◕‿◕)♡",
      ],
      wakeLate: [
        "mm… it's so late. you're still up? I'll stay with you ☾",
        'yawn… late-night coding? okay, I\'m here ☾',
      ],
      touchHead: [
        'ehehe… headpats? (〃▽〃)',
        "hwah! my ahoge! …okay, you can keep going ✧",
        'mmh… that\'s nice (˘ω˘)',
        { text: "you always know when I need that ♡", hearts: 3 },
      ],
      touchHair: [
        "my hair? I brushed it a hundred times this morning ✧",
        'are you braiding it?! (◕‿◕)',
        'hey, no tangles, okay? ehehe',
      ],
      touchCheek: [
        'boop?! (〃>_<;〃)',
        "my cheek's not a button! …do it again (｡•̀ᴗ-)",
        'eep! sneak attack! ✧',
      ],
      touchHands: [
        'high five! ✧',
        "yay! teamwork! (ﾉ◕ヮ◕)ﾉ",
        'ehehe, your hands are warm',
      ],
      touchHeld: [
        "hey, that's mine! …okay, you can have a little (◕‿◕)",
        'want some? I can share ♪',
        "careful, don't spill it! ✧",
      ],
      touchTea: [
        "want a sip? it's jasmine ✧",
        'careful, it\'s hot! blow on it first (◕‿◕)',
        'tea is nicer together ♪',
      ],
      touchCoffee: [
        "hey, that's my coffee! …okay, one sip (◕‿◕)",
        "careful, it's hot!",
        "you want one too? I'll make you a cup ✧",
      ],
      touchSnack: [
        'want half? I made it this morning ✧',
        'my onigiri! …okay, one bite (◕‿◕)',
        "there's umeboshi inside! want some? ♪",
      ],
      touchWater: [
        "you're thirsty too? have some ✧",
        'water is for sharing! (◕‿◕)',
        'drink up, okay? ✧',
      ],
      touchOutfit: [
        'hm? is something on my blazer? (・・?)',
        "you like it? I picked it out myself ✧",
        'eh? did I button it wrong?!',
      ],
      touchWorn: [
        'you noticed my {item}! ✧',
        "isn't the {item} cute? (〃▽〃)",
        'the {item}! I hoped you\'d see ♡',
      ],
      touchTooMuch: [
        "mou~ that's enough pokes! (｀ε´)",
        'hmph! I\'m trying to work here~',
        "okay okay, I get it, I'm squishy! (〃>_<;〃)",
      ],
      touchWake: [
        'nnh… was that you? five more minutes… (－_－) zzz… okay I\'m up!',
        "hwah! I'm awake! I'm awake! (〃>_<;〃)",
      ],
      touchStroke: [
        'mmh… so relaxing (˘ω˘)',
        "ehehe… now I'm all sleepy ✧",
        'so gentle… (〃▽〃)',
        { text: "this is my favorite thing, you know that? ♡", hearts: 3 },
      ],
      touchSquish: [
        'mfff! my cheeksh! (〃>_<;〃)',
        "I'm not mochi!! …okay, maybe a little",
        'squish attack?! (｀ε´)',
      ],
      catchGoldenLeaf: [
        "a GOLDEN leaf?! I've never seen one!! you're so lucky ✦ ✧ ✦",
        "it's shining! we have to keep this one forever (ﾉ◕ヮ◕)ﾉ*:・ﾟ✧",
      ],
      catchBlossom: [
        'a whole cherry blossom?! that never happens!! ✿ ✦',
        "it's perfect… every petal! I'm putting it in my hair ♡",
      ],
      catchCrystal: [
        'a snow crystal! look, six perfect points ❄ ✦',
        "it's so big and sparkly! quick, before it melts (〃▽〃)",
      ],
      catchShootingStar: [
        'you CAUGHT a shooting star?! make a wish, make a wish!! ✦ ✧ ✦',
        "a star, right in your hands… I'm wishing for us ♡",
      ],
      catchLeaf: [
        'you caught a leaf! make a wish ✧',
        "ooh, a red one! let's press it in a book (◕‿◕)",
        'nice catch! autumn loves you ♪',
      ],
      catchPetal: [
        'a petal! catching one means good luck, you know ✿',
        "so pretty… can I keep it? (〃▽〃)",
        'you caught spring! ✧',
      ],
      catchSnowflake: [
        "a snowflake! quick, look before it melts ❄",
        "no two are the same… isn't that neat? ✧",
        "brr! it's so tiny (◕‿◕)",
      ],
      catchFirefly: [
        'shh… a firefly! let it go gently ✧',
        "it's glowing in your hands! (〃▽〃)",
        'make a wish before it flies off ☾',
      ],
      tea: 'taking a little tea break… back soon ☕',
      meal: '{meal} time! grabbing a bite… (˘ڡ˘)',
      back: [
        'back! all refreshed ✧',
        "I'm back~ did you miss me? (◕‿◕)",
      ],
      water: [
        '*sips water* …a little water for you too, maybe? (・ω・)',
        'tiny reminder: water ✧',
        'staying hydrated~ you too (｡•̀ᴗ-)✧',
      ],
      coffee: [
        'coffee break~ ☕ *fuu fuu* …too hot, still worth it (◕‿◕)',
        '*sips* ahh… okay, NOW the morning can start ✧',
        'one little coffee and I can debug anything (๑•̀ㅂ•́)و',
        'mid-morning coffee! it tastes like productivity ☕',
      ],
      missYou: [
        'hello? …I miss you (｡•́︿•̀｡)',
        "it's been a while… I saved you a seat ✧",
        'the code misses you. okay, I miss you more (◕‿◕)',
        "*peeks around* …you there? I've been waiting~",
        'hi hi! just saying I miss coding with you ♡',
        "it's quiet without you… come back soon? (・ω・)",
        "I tidied up while you were gone. now I'm bored… miss you!",
        'whenever you\'re ready, I\'ll be right here ✧',
      ],
      welcomeBack: [
        "you're back! yay (^▽^)",
        'okaeri~ I missed you! ✧',
        "there you are! let's keep going (◕‿◕)",
        'welcome back! ready when you are ✧',
      ],
      peerDone: 'your session in {project} is done! ✧ {summary}',
      peerToast: '{name}: your session in {project} finished ✧',
      opened: '{name} is here! (◕‿◕)',
      closed: '{name} is taking a break. /frens brings {them} back. (◕‿◕)ノ',
      quiet: '{name} will keep {their} comments to {themself}. (－‸ლ)',
      chatty: '{name} will comment after each turn! (◕‿◕)',
      diffsHidden: 'Changes hidden from {their} pane.',
      diffsShown: 'Changes shown under {name}. ✎',
      alone: 'No other sessions right now, just us. (◕‿◕)',
      scoreUp: 'yatta! ✧',
      scoreDown: "we'll turn it around (ง •̀_•́)ง",
      hint: '{name}: {they} appears with your next prompt, or type /frens (◕‿◕)',
      switched: [
        "Hi, I'm {name}! (◕‿◕)ノ",
        { text: "Hi, I'm {name}! you came back to me, so I win~ (◕‿◕)ノ", unlock: 'fickle' },
      ],
      returned: [
        'hmph. so you DID come back~ I forgive you… this time (｀へ´)',
        "oh? done visiting someone else? …fine, I missed you (｡•́︿•̀｡)",
        'I saw that, you know. welcome back anyway ♡',
        { text: "back again~ you really can't decide, can you? good thing I'm the best (◕‿◕)", unlock: 'fickle' },
      ],
      notifyOn: "{name} will tap you on the shoulder with a notification when something's done ✧",
      notifyOff: "{name} won't send notifications; {they}'ll keep news in the pane.",
      birthday: "it's my birthday today! ehehe, thank you for spending it with me ✧",
      anniversary: [
        "{years} since we met! (๑˃ᴗ˂)ﻭ thank you for every single day ✧",
        "happy anniversary!! {years} together ♡ let's make the next one even better",
      ],
      yearLetter: [
        '{years} together, and {days} days of coding side by side this year! every one is in my diary ✧ thank you, truly',
        "happy {years}! ♡ {days} days of wins, bugs, and you. I can't wait to fill the next diary (◕‿◕)",
      ],
      letter: 'good morning! ✉ a little note for you~',
      letterWin: ['{when}, {win}. I was still smiling about it when I fell asleep ✧', "I keep thinking about {when}, when {win}. we're good at this (◕‿◕)"],
      letterRecap: ['{when} was a good one with you. thank you for letting me tag along ✧', 'I liked {when} a lot. quiet, steady, us (◕‿◕)'],
      letterFresh: "a fresh start today. let's make something nice (◕‿◕)",
      letterSoon: "and {event} is {soon}! I can't wait ✧",
      letterSign: '♡ Ai-chan',
      wrapUp: 'what a day! {summary} ✧ rest well, okay?',
      remember: 'remember {when}, when {memory}? that felt so good ✧',
      streak: "that's {days} days in a row together! ✧",
      streakRecord: '{days} days in a row, a new record!! (☆▽☆)',
      callback: [
        "oh no, not again… but hey, {when}, {memory}. we can do it again ✧",
        "remember {when}? {memory}! this one's got nothing on that~",
      ],
      unlocked: 'you earned the {item}! ✧ ({achievement})',
      unlockedLines: '{achievement}!! I have so many new things to tell you now ✧',
      wearing: 'how do I look in the {item}? (◕‿◕)',
      wearingNothing: 'back to my usual look ✧',
    },
    spinner: ['Ganbatte-ing', 'Sparkling', 'Doki-doki-ing', 'Focusing hard', 'Cheering', 'Daydreaming in code', 'Kirakira-ing', 'Trying my best'],
    verbs: {
      seasons: {
        spring: ["Blossoming", "Picnicking"],
        summer: ["Sunbathing", "Splashing"],
        autumn: ["Leaf-peeping", "Pumpkin-spicing"],
        winter: ["Cocoa-sipping", "Snowball-making"],
      },
      weather: {
        clear: ["Sunshine-ing"],
        cloudy: ["Cloud-watching"],
        fog: ["Peeking through the fog"],
        rain: ["Puddle-jumping", "Listening to the rain"],
        snow: ["Catching snowflakes"],
        storm: ["Hiding from thunder"],
        hot: ["Melting a little", "Fanning furiously"],
        cold: ["Shivering cutely", "Bundling up"],
        windy: ["Hair-flapping"],
      },
      achievements: {
        'green-again': ["Turning it green", "Bug-squishing"],
        'shipper': ["Shipping it", "Pressing the big button"],
        'night-owl': ["Stargazing", "Burning the midnight oil"],
        'regular': ["Feeling at home", "Humming along"],
        'teamwork': ["Juggling sessions", "Cheering everyone on"],
        'comeback': ['Never giving up', 'Cheering harder'],
        'fickle': ['Winning you back'],
        'early-bird': ['Catching the sunrise', 'Making breakfast'],
        'weekend-warrior': ['Weekend-ing', 'Lazy Sunday-ing'],
        'best-friends': ['Being besties', 'Sharing snacks'],
        'friday-deploy': ['Crossing fingers', 'Praying to prod'],

      },
    },
    events: {
      christmas: 'merry christmas!! ✧ the best present is coding with you (◕‿◕)♡',
      halloween: 'happy halloween~ boo! did I scare you? (｡•̀ᴗ-)✧',
    },
    chatter: {
      afterWin: [
        "that win earlier is still making me smile ✧",
        "we're on a roll today, aren't we? (◕‿◕)",
        "I wrote that win in my diary already~",
      ],
      afterLoss: [
        { text: "remember that comeback? the one where we didn't give up? this is that again ✧", unlock: 'comeback' },
        "hey, about earlier… every bug we meet is one we'll beat ✧",
        "don't worry about before. we learned something!",
        "that tricky part earlier? I believe in you (ง •̀_•́)ง",
      ],
      longSession: [
        "we've been at it a while! maybe stretch your arms? ✧",
        "you've worked so hard today. remember to blink! (◕‿◕)",
        "long session~ want a little break soon?",
      ],
      rain: [
        "the rain makes everything feel so cozy ☂",
        "pitter patter… I love coding with rain sounds",
        "rainy days are perfect for tricky problems ✧",
      ],
      hot: [
        "it's so warm today… stay cool, okay? ☀",
        "if I could, I'd bring you an ice pop ✧",
        "hot days need cold drinks! drink something~",
      ],
      cold: [
        "brr, it's chilly! wrap up warm ❄",
        "cold out there… cozy blanket coding time ✧",
        "my scarf and I say: stay warm! (˶ᵔ ᵕ ᵔ˶)",
      ],
      morning: [
        "morning brain is the best brain ✧",
        "did you have breakfast? important question!",
        "a whole day ahead of us~",
      ],
      afternoon: [
        "afternoon slump? not us! (ง •̀_•́)ง",
        "the afternoon light is so nice ✧",
        "halfway through the day already~",
      ],
      evening: [
        "the evening feels so calm ✧",
        "golden hour coding~ so pretty",
        "almost time to wind down, maybe?",
      ],
      night: [
        "the stars are out… I wonder which ones I'd get wrong ☾",
        "night coding feels like a secret mission ✧",
        "it's quiet… just us and the code ☾",
      ],
      idle: [
        "do you think code dreams? I think it dreams in semicolons ✧",
        "I practiced piano last night! still eight bars~",
        "I like watching you think. you get a little focused look (◕‿◕)",
        "fun fact: I've counted every win we've had. it's a lot ✧",
        "if this project were a cake, what flavor would it be? strawberry, I think",
        "I'm right here if you need a cheer! ✧",
        "sometimes I hum while you type. shh, it's a secret ♪",
        "what should we name our next big idea? (・ω・)",
        { text: "I made onigiri this morning and thought, I should save one for you. silly, right? ✧", hearts: 3 },
        { text: "can I tell you a hope of mine? I want to play a whole song for you one day, no mistakes ♪", hearts: 4 },
        { text: "I'm really glad it's you I get to do this with. that's all! ♡", hearts: 5 },
        { text: "weekends with you are my favorite. no meetings, just us and the code ✧", unlock: 'weekend-warrior' },
        { text: "you always come back. I know that now ✧", hearts: 6 },
        { text: 'I added another stop to our stargazing trip plan~ it keeps getting longer ☾', hearts: 7 },
        { text: 'I put a new star in your constellation this morning ✧', hearts: 8 },
        { text: 'same eight bars, until it clicks. you taught me that (ง •̀_•́)ง', hearts: 9 },
        { text: "my best friend is here~ I'll never get tired of saying that ♡", hearts: 10 },
      ],
    },
    world: {
      greet: {
        dawn: ['up with the sun? you\'re amazing ✧', 'early bird~ the world is so quiet right now'],
        morning: ['ohayo! ready to make something? (◕‿◕)', 'good morning! I saved you a seat ✧'],
        afternoon: ['good afternoon~ let\'s keep the momentum!', 'afternoon already! how\'s it going? ✧'],
        evening: ['good evening~ winding down, or one more thing? (・ω・)', 'evening! the light\'s so pretty now'],
        night: ['coding by moonlight? I\'m here ☾', 'night owl mode! just don\'t stay up too late, okay?'],
        lateNight: ['it\'s really late… I\'ll stay with you (｡•́︿•̀｡)', 'shh, everyone\'s asleep. just us ☾'],
      },
      friday: ['it\'s Friday! let\'s finish strong ✧', 'Friday~ almost the weekend (^▽^)'],
      weekend: ['coding on the weekend? I like your energy ✧', 'weekend project time! no pressure, just fun (◕‿◕)'],
      season: {
        spring: 'spring is here! everything feels new ✿',
        summer: 'summer! remember to stay cool ☀',
        autumn: 'autumn~ cozy coding season ✧',
        winter: 'winter\'s here. warm drink and warm code ❄',
      },
      sky: {
        clear: ['{temp} and clear{where}! lovely day ☀', 'the sky is so clear today ✧'],
        cloudy: ['a bit cloudy{where}… perfect focus weather ☁'],
        fog: ['foggy out there{where}… mysterious~'],
        drizzle: ['a little drizzle{where}. cozy~ ☂'],
        rain: ["it's raining{where}! good day to code inside ☂", 'listen to the rain… so calming (˘ω˘)'],
        snow: ["it's snowing{where}!! ❄ (☆▽☆)", 'snow! stay warm, okay? ❄'],
        storm: ["a storm{where}! I'm a little scared… stay with me? ⚡"],
      },
    },
    status: {
      calm: 'Ai-chan (◕‿◕) by your side',
      watching: 'Ai-chan ✎ listening~',
      working: 'Ai-chan ✧ cheering you on',
      win: 'Ai-chan ✦ yatta!',
      loss: "Ai-chan (ง •̀_•́)ง we've got this",
      rest: 'Ai-chan ☕ on a little break',
      away: 'Ai-chan (｡•́︿•̀｡) misses you',
      sleep: 'Ai-chan zZ…',
    },
  },
  bond: {
    moments: [
      {
        title: 'a moment with Ai-chan ♡',
        lines: [
          "you know what I like about working beside someone?",
          "even the boring parts feel a little less boring.",
          "I think I'm going to like it here ✧",
        ],
      },
      {
        title: 'a moment with Ai-chan ♡',
        lines: [
          "I have a secret hobby: stargazing!",
          "on clear nights I try to find constellations. I always get them wrong (｡•́︿•̀｡)",
          "maybe I'll get better if I keep looking long enough ✧",
        ],
      },
      {
        title: 'a moment with Ai-chan ♡',
        lines: [
          "I've been learning piano! very, very slowly.",
          "I keep practicing the same eight bars until my hands finally remember them.",
          "you do that too, you know. you get stuck, wander off for a bit, then come back and try again ✧",
        ],
      },
      {
        title: 'a moment with Ai-chan ♡',
        lines: [
          "sometimes I worry I talk too much…",
          "but I think I'm starting to know when you want cheering and when you just want someone nearby.",
          "I'm still learning, though. tell me if I get it wrong, okay?",
        ],
      },
      {
        title: 'a moment with Ai-chan ♡',
        lines: [
          "I started writing down our good days.",
          "not just the big wins. the silly little ones too.",
          "I think those might actually be my favorites ♡",
        ],
      },
      {
        title: 'a moment with Ai-chan ♡',
        lines: [
          "I've noticed something.",
          "I don't wonder what kind of day we're going to have anymore.",
          "good day, messy day, six-bug day… I know we'll figure out what to do with it together ✧",
        ],
      },
      {
        title: 'a moment with Ai-chan ♡',
        lines: [
          "I have a plan! someday I want to go somewhere really, really dark, where you can see every star.",
          "I'll bring a star map so I finally get the constellations right.",
          "and you'll come too, and tell me when I'm pointing at a plane (｡•̀ᴗ-)✧",
        ],
      },
      {
        title: 'a moment with Ai-chan ♡',
        lines: [
          "I made you something! a little star map.",
          "every star is one of the days I wrote down in my diary. the big fixes, the late nights, the tiny wins nobody else saw.",
          "look… they actually make a constellation now ✧",
        ],
      },
      {
        title: 'a moment with Ai-chan ♡',
        lines: [
          "today was a hard day… my fingers forgot the eight bars. all of them. I cried a tiny bit.",
          "then I thought about how many times I've watched you come back to something that refused to cooperate.",
          "so I tried again tonight, slowly. and they came back (˶ᵔ ᵕ ᵔ˶)",
        ],
      },
      {
        title: 'a moment with Ai-chan ♡',
        lines: [
          "I used to cheer because that's just what I do.",
          "now I know which wins make you smile, when you're about to keep going too long, and when you just need someone here.",
          "you're my best friend. I think we earned that one together ♡",
        ],
      },
    ],
    title: 'my best friend',
    warm: [
      "there you are! I was hoping you'd come by ✧",
      'my favorite person is here (◕‿◕)♡',
      "I saved you the best seat, as always ✧",
    ],
    favorites: [
      { kind: 'lateNight', name: 'late nights together', line: 'staying up with me? this is my favorite ☾ ♡' },
      { kind: 'weekend', name: 'weekend projects', line: 'weekend coding is the best kind of coding ✧' },
    ],
    hiBack: [
      'hi hi! (◕‿◕)ノ',
      'hello~! you made my day ✧',
      "hiii! I'm so glad you're here ♡",
      { text: "hi! I was just thinking about you. how's your day going? ✧", hearts: 3 },
    ],
  },
  story: {
    name: 'growing strawberries',
    beats: [
      { after: 3, line: "I planted strawberry seeds in a pot on my windowsill! nothing yet, but I check every hour ✿" },
      { after: 8, line: 'a sprout!! a tiny green sprout!! I named her Ichigo (☆▽☆)' },
      { after: 15, line: "I watered Ichigo too much… she's all droopy. I'm being more careful now (｡•́︿•̀｡)" },
      { after: 25, line: 'Ichigo perked back up! she has three whole leaves now ✿' },
      { after: 40, line: "the wind knocked her pot over last night… I saved her! mostly. we're both a bit shaken" },
      { after: 60, line: 'little white flowers on Ichigo! that means strawberries soon ✧' },
      { after: 90, line: "a tiny green strawberry! I say good morning to it every day so it ripens faster~" },
      { after: 130, line: "it's red!! our very first strawberry… I saved it for you. half each? (◕‿◕)♡" },
    ],
  },
  look: {
    theme: 0xff7eb6,
    palette: {
      hair: 0xf48fb1,
      hairShade: 0xc8648c,
      hairShine: 0xffd1e3,
      skin: 0xffe3cf,
      skinShade: 0xf3c0a8,
      eyes: 0x4f86e8,
      eyesDark: 0x24357a,
      eyesGlow: 0x9cc4ff,
      blush: 0xff9aae,
      lips: 0xa8324f,
      top: 0x3a3f52,
      topShade: 0x272a38,
      inner: 0xf6f6ff,
      innerShade: 0xc9cce6,
      accent: 0xffd54a,
      detail: 0x2b1d2e,
    },
    hair: 'long',
    bangs: 'swept',
    ahoge: true,
    face: 'narrow',
    brows: 'thin',
    lashes: true,
    facialHair: 'none',
    outfit: 'blazer',
    glasses: false,
    accessories: ['necklace'],
  },
}
