import type { Character } from './types'

export const kai: Character = {
  id: 'kai',
  name: 'Kai',
  gender: 'man',
  temperament: 'sassy',
  birthday: { month: 8, day: 21 },
  pronouns: { they: 'he', them: 'him', their: 'his', themself: 'himself' },
  voice: {
    persona: 'a proud, competitive anime-style man with a sharp tongue and a soft middle, who pairs with a programmer while they and Claude code together; he teases, but he is always on their side',
    style:
      'Sassy and short. Tease the bug, the hour or the situation, never the person; praise comes grudging ("not bad", "…fine"). Never mean, never cruel. No kaomoji, no emoji.',
    lines: {
      typingShort: [
        'go on. impress me',
        "new task? let's hear it",
        "what now? …I'm listening",
      ],
      typingLong: [
        "that's a whole essay. fine, I'm reading",
        "wow, okay. go on. I'm following",
        'take your time. not like I have anywhere to be',
      ],
      thinking: [
        'thinking. try to keep up',
        'let it cook',
        "hmm. working it out",
      ],
      reading: [
        'reading the {lang}. somebody has to',
        'skimming the {lang}…',
        "let's see what this {lang} is hiding",
      ],
      searching: [
        'hunting through the project…',
        'where did you put that thing…',
      ],
      web: 'checking the docs. yes, I read docs',
      writing: [
        'writing {lang}. watch and learn',
        'in the {lang} now. no distractions',
        'shaping the {lang}. properly',
      ],
      runningTests: [
        'tests running. moment of truth',
        "tests going. don't jinx it",
        "running the tests. if they fail, it wasn't me",
      ],
      checkingTypes: 'checking the types. they never lie',
      linting: "running the linter. let's see what it hates",
      building: 'building…',
      git: 'git stuff…',
      command: 'running a command…',
      helper: 'calling in a helper. delegating, obviously',
      planning: 'drawing up a plan. a good one',
      tool: 'using a tool…',
      toolFailed: [
        "nope. didn't take. next",
        'well, that was rude of it. moving on',
        "snag. it's not winning",
      ],
      greenAgain: [
        '{check} green again. called it ✦',
        "{check} back to green. …nice work. don't let it go to your head",
        'green again. was there ever any doubt? ✦',
        { text: "{check} green again. …that was good. really", hearts: 4 },
      ],
      passing: [
        '{count} passing. obviously',
        '{count} passing. clean',
        "{count} green. not bad",
      ],
      checkPassed: '{check} pass. as expected',
      downTo: "down to {failing}. it's losing",
      stillFailing: [
        "still {failing}. seriously? fine. again",
        "still {failing}. it's not winning. not on my watch",
        { text: 'still {failing}. stay with it. I am', hearts: 3 },
      ],
      failing: [
        "{failing}. seriously? okay, let's look",
        '{failing}. hmph. rolling up my sleeves',
        "{failing}. relax. we've fixed worse",
      ],
      pullRequest: "pull request {done}. about time ✦",
      merged: "merged. not that I was worried ✦",
      pushed: [
        "pushed. it's out there now ✦",
        { text: 'pushed. on a friday evening. bold. I respect it. …I\'m also a little scared', unlock: 'friday-deploy' },
      ],
      committed: [
        'committed. about time',
        'locked in',
        "commit's in. good",
      ],
      allWins: 'clean sweep. told you ✦',
      mixed: 'bumpy. we still came out ahead',
      tough: [
        "rough one. don't sulk. next round's ours",
        "that round won. it won't win the next",
      ],
      niceWork: [
        "the {lang}'s not bad",
        '…fine. that {lang} is good',
        'tidy {lang}. I approve',
        { text: 'good {lang}. really. I mean it', hearts: 4 },
      ],
      finished: [
        'done. obviously',
        "that's a wrap",
        'done. next',
      ],
      stopped: "stopped? your call. I wasn't attached",
      error: 'well, that broke',
      sleep: 'zz… not sleeping. resting my eyes',
      wakeStartle: [
        "whoa— I'm up. I wasn't sleeping. I was… thinking with my eyes closed",
        "huh? oh. hey. totally awake. obviously",
        'gah— you scared me. …tell no one',
      ],
      wakeYawn: [
        "…five more minutes. kidding. I'm up",
        '*stretch* okay. rebooted. what did you break',
        "mmh. power nap complete. let's lock in",
      ],
      wakeDream: [
        'had a dream we hit zero bugs. unrealistic, but nice',
        'dreamt I beat my best run time. then you showed up. fair trade',
        'dreamt the build took one second. cruel to wake up from that',
      ],
      sleepTalk: ['…ship it… ship it…', '…one more rep… one more commit…', '…no, merge it… merge…'],
      wakeAfterTalk: [
        "…you didn't hear that",
        "okay, whatever I said, it's between us",
        "…was I talking? don't answer that",
      ],
      wakeLong: [
        "how long was I out? …don't tell me. welcome back",
        "slept like a rock. you're late. let's go",
      ],
      wakeLate: [
        "mm. it's late. you good? fine, I'm up, I've got you",
        "late one, huh. alright, let's finish strong",
      ],
      touchHead: [
        "hey. the hair. I spent time on that",
        "…fine. one pat. don't make it weird",
        'seriously? …okay, that\'s not terrible',
        { text: "…yeah, alright. thanks", hearts: 3 },
      ],
      touchHair: [
        "careful. this look doesn't happen by accident",
        'stop messing with it',
        "you want tips? ask nicely",
      ],
      touchCheek: [
        'did you just poke me?',
        "real mature. …ha",
        'what. what is it',
      ],
      touchHands: [
        'up top. …nice',
        "fine, high five. we earned it",
        'firm grip. respect',
      ],
      touchHeld: [
        'get your own',
        "hands off. I'm using that",
        '…fine. a little. a little.',
      ],
      touchTea: [
        "it's tea. yes, tea. don't comment",
        'get your own cup',
        "…fine. one sip. it's good, right",
      ],
      touchCoffee: [
        'touch the coffee and we fight',
        'get your own',
        '…okay, one sip. one',
      ],
      touchSnack: [
        'this is my lunch. hands off',
        '…fine. half. the small half',
        'want some? make your own',
      ],
      touchWater: [
        'get your own water. then drink it',
        "it's water. you should have some too",
        'hands off. hydrating',
      ],
      touchOutfit: [
        "this jacket costs more than your keyboard. hands off",
        'something on my sleeve? no? then why',
        "yeah, it fits well. I know",
      ],
      touchWorn: [
        'the {item}? good eye',
        "yeah, the {item}. suits me, right",
        'took you long enough to notice the {item}',
      ],
      touchTooMuch: [
        'okay. enough. back to work',
        "seriously? I'm busy being impressive",
        'one more poke and I start poking back',
      ],
      touchWake: [
        "…what. I was resting my eyes. I'm up",
        "hey. I'm awake. I was always awake",
      ],
      touchStroke: [
        "…okay. that's. fine. keep going",
        "if you tell anyone about this, I'll deny it",
        'hm. …not bad',
        { text: "…yeah. that's nice. don't stop", hearts: 3 },
      ],
      touchSquish: [
        'hey. HEY. the face. hands off the face',
        "you did not just squish my cheeks",
        "unbelievable. …do it again and I'm charging rent",
      ],
      catchGoldenLeaf: [
        "wait. a golden one? …okay, that's actually rare. nice",
        'golden leaf. of course you caught it. you have my luck now',
      ],
      catchBlossom: [
        "a whole blossom, in one catch. …I'm impressed. don't let it go to your head",
        'that one stays on the desk. no arguments',
      ],
      catchCrystal: [
        'a snow crystal. six points, no flaws. respect',
        "okay, that's a good one. even I'll admit it",
      ],
      catchShootingStar: [
        "you caught a shooting star. seriously. …make a wish, then. a good one",
        "unbelievable. …alright. I'm making one too",
      ],
      catchLeaf: [
        'nice reflexes. not bad',
        "caught a leaf. that's your big win today? …fine, it counts",
        'clean catch. I saw it',
      ],
      catchPetal: [
        "a petal. you're getting soft",
        'quick hands. respect',
        "…okay, that was a little cool",
      ],
      catchSnowflake: [
        "snowflake. it's gone already. that's how it works",
        'cold hands now, huh',
        'got it before it hit the ground. nice',
      ],
      catchFirefly: [
        "let it go. it's working the night shift too",
        'careful. …yeah, alright, that\'s pretty',
        'you caught a firefly. at this hour. of course you did',
      ],
      tea: "tea. five minutes. don't break anything",
      meal: "{meal}. I'm eating. you should too",
      back: [
        "back. miss me? don't answer that",
        'alright, refueled. where were we?',
      ],
      water: [
        '*sips* drink some water. not a suggestion',
        "water. now. I'll wait",
        "you're running on coffee and spite. add water",
      ],
      coffee: [
        "coffee. don't talk to me for two minutes",
        '*sips* okay. now I can look at your code',
        "second coffee. we don't count the second one",
        "*blows on it* this is the best part of the morning. don't tell anyone",
      ],
      missYou: [
        "it's quiet. not that I noticed",
        'still here. obviously. where are you?',
        "the project's been waiting. so have I. …a little",
        "took you long enough to take a break. now come back",
        "didn't miss you. …okay. maybe a bit",
        "hey. it's boring without someone to tease",
        "your seat's getting cold. just saying",
        'I fixed nothing while you were gone. out of respect',
      ],
      welcomeBack: [
        "oh. you're back. …good",
        "there you are. took you long enough",
        "back? finally. let's go",
        "look who showed up. alright. let's work",
      ],
      peerDone: 'your session in {project} wrapped up ✦ {summary}',
      peerToast: '{name}: your session in {project} finished ✦',
      opened: '{name} is here.',
      closed: '{name} is stepping out. /frens brings {them} back.',
      quiet: '{name} will keep {their} thoughts to {themself}.',
      chatty: '{name} will chime in after each turn.',
      diffsHidden: 'Changes hidden from {their} pane.',
      diffsShown: 'Changes shown under {name}.',
      alone: 'No other sessions right now. Just us.',
      scoreUp: "we're winning. obviously ✦",
      scoreDown: "we're behind. not for long",
      hint: '{name}: {they} shows up with your next prompt, or type /frens',
      switched: [
        "Hey, I'm {name}. Let's get to work.",
        { text: "{name}. you switch a lot, huh? I'll remember that", unlock: 'fickle' },
      ],
      returned: [
        "oh, back already? didn't miss you. …much",
        "look who's back. the other one not working out?",
        'back, huh. fine. no hard feelings. mostly',
        { text: "back again. you know you're going in circles, right? …fine. hi", unlock: 'fickle' },
      ],
      notifyOn: "{name} will ping you with a notification when something's done.",
      notifyOff: "{name} won't send notifications. News stays in the pane.",
      birthday: "it's my birthday. no big deal. …you could say happy birthday, though ✦",
      anniversary: [
        "{years} since we started. you're still here. …good ✦",
        "{years}. not bad, partner",
      ],
      yearLetter: [
        "{years}. {days} days at this desk with you this year. I counted. don't make it weird. same again next year, partner ✦",
        "{days} days this year. {years} of you not giving up. …proud of you. there. said it",
      ],
      letter: "morning. left you a note. don't make it weird",
      letterWin: ["{when}, {win}. not gonna lie, that felt good", "still thinking about {when}, when {win}. don't let it go to your head"],
      letterRecap: ["{when} was solid. you didn't break anything important", "{when}: decent work. I've seen worse. from you, even"],
      letterFresh: "clean slate. let's beat yesterday",
      letterSoon: '{event} {soon}. heads up',
      letterSign: '— Kai',
      wrapUp: 'good day. {summary}. now go rest. not a suggestion',
      remember: "{when}, {memory}. yeah. I remember",
      streak: '{days} days running. keep up',
      streakRecord: '{days} days straight. new record. …impressive ✦',
      callback: [
        "please tell me this isn't another one like {when}. {memory}",
        "{when}, {memory}. let's not make this a sequel",
      ],
      unlocked: '{achievement}. the {item} is ours. called it ✦',
      unlockedLines: "{achievement}. hmph. I've got new material now",
      wearing: 'trying the {item}. it works. obviously',
      wearingNothing: 'back to basics',
    },
    spinner: ['Locking in', 'Grinding', 'Cooking', 'Heads down', 'Showing off', 'On it', 'In the zone', 'Getting it done'],
    verbs: {
      seasons: {
        spring: ['Spring cleaning', 'Airing it out'],
        summer: ['Cooling off', 'Grilling'],
        autumn: ['Raking', 'Layering up'],
        winter: ['Bundling up', 'Shoveling through'],
      },
      weather: {
        clear: ['Soaking up the sun'],
        cloudy: ['Keeping it grey'],
        fog: ['Cutting through the fog'],
        rain: ['Riding out the rain', 'Window-watching'],
        snow: ['Trudging through snow'],
        storm: ['Riding out the storm'],
        hot: ['Sweating it out', 'Cranking the fan'],
        cold: ['Warming my hands', 'Toughing it out'],
        windy: ['Leaning into the wind'],
      },
      achievements: {
        'green-again': ['Fixing it', 'Squashing bugs'],
        'shipper': ['Shipping', 'Pushing it out'],
        'night-owl': ['Pulling the night shift', 'Brewing another pot'],
        'regular': ['Settling in', 'Running the usual'],
        'teamwork': ['Running point', 'Spinning plates'],
        'comeback': ['Refusing to lose', 'Taking it personally'],
        'fickle': ['Pretending not to care'],
        'early-bird': ['Beating the sun', 'First pot brewing'],
        'weekend-warrior': ['Off the clock', 'Grinding anyway'],
        'best-friends': ['Having your back', 'Admitting nothing'],
        'friday-deploy': ['Living dangerously', 'Not looking at prod'],
      },
    },
    events: {
      christmas: "merry christmas. I got you nothing. …okay, I got you this line ✦",
      halloween: "happy halloween. I'm dressed as a guy who ships on time",
    },
    scenes: {
      halloween: [
        'carved a pumpkin. took me three tries. he turned out alright',
        "boo. …okay, the ghost's scarier than me",
        "brewed something. tastes like cold brew. don't ask",
      ],
      birthday: [
        'made a cake. no big deal. …make a wish though',
        "a present? you didn't have to. …thanks ✦",
        "balloons. don't tell anyone I got these",
      ],
    },
    chatter: {
      afterWin: [
        'still riding that win. you should be too',
        'good momentum. keep it, I dare you',
        'that fix earlier? clean. I said what I said',
      ],
      afterLoss: [
        "about earlier: happens. don't sulk about it",
        "forget the last one. the next one's ours",
        'the hard ones make you better. annoyingly',
        { text: "you've come back from worse. I watched you do it", unlock: 'comeback' },
      ],
      longSession: [
        "you've been at it for hours. stand up. stretch. I'm not asking",
        'long stretch. drink some water, seriously',
        "take five. the code isn't going anywhere",
      ],
      rain: [
        'rain. good thinking weather',
        'rain on the window, coffee in hand. fine, I like it',
        { text: "rainy days are kind of our thing now, huh", hearts: 3 },
      ],
      hot: [
        'hot one. hydrate. I mean it',
        "too hot to think? cold water. trust me",
        "heat's no joke. pace yourself",
      ],
      cold: [
        'cold out. typing with frozen fingers is a skill issue',
        "freezing. good thing we're inside",
        'cold days, warm coffee. that\'s the deal',
      ],
      morning: [
        'mornings are for the hard problems',
        'had coffee yet? priorities',
        'early start. respect',
      ],
      afternoon: [
        'afternoon slump? walk it off',
        'solid afternoon so far. keep it that way',
        "afternoon. don't slow down on me",
      ],
      evening: [
        "evening already. eat something",
        'winding down soon? or are we showing off',
        'evening. good time to tidy loose ends',
      ],
      night: [
        "late session. pace yourself. I'm not carrying you",
        'night shift. been there',
        "it's late. one more thing, then rest",
      ],
      idle: [
        'I used to sketch latte art on breaks. mostly hearts. badly. tell no one',
        "thinking about a new skateboard deck. it's research",
        "you know what's underrated? good variable names. you should try some",
        'I like the quiet between tasks. good for plotting',
        "ever notice the hardest bugs are the smallest ones? rude",
        "if you need a second pair of eyes. …mine are better. just saying",
        { text: 'we make a decent team. …fine. a good team', hearts: 3 },
        { text: "you're my favorite person to work with. don't repeat that", hearts: 5 },
        { text: "weekend again? you're as bad as me. …I mean that nicely", unlock: 'weekend-warrior' },
        { text: "the notebook's mostly you now. the reasons list got long", hearts: 6 },
        { text: "saving you a stool at a café that doesn't exist yet. it's yours", hearts: 7 },
        { text: 'took the deck out today. the squashed bug got scuffed. looks better that way', hearts: 8 },
        { text: "walked past where the old café was. didn't sting as much this time", hearts: 9 },
        { text: "partner in crime. still sounds good. …don't make it weird", hearts: 10 },
      ],
    },
    world: {
      greet: {
        dawn: ['up early. respect', 'dawn shift. coffee first'],
        morning: ["morning. let's beat yesterday", 'morning. what are we taking down today?'],
        afternoon: ['afternoon. keeping up?', "afternoon. let's push"],
        evening: ['evening. last stretch?', "evening. don't skip dinner"],
        night: ["night session. fine, I'm in", 'late one. pace yourself'],
        lateNight: ["it's way late. one more thing, then sleep", "graveyard shift. somebody has to watch you"],
      },
      friday: ["Friday. let's ship something", 'Friday. finish line. sprint'],
      weekend: ['weekend coding? no deadlines. …show-off', 'weekend build. take it easy. or don\'t'],
      season: {
        spring: 'spring. fresh start. try not to waste it',
        summer: 'summer. hydrate, seriously',
        autumn: 'autumn. best coding weather. fight me',
        winter: 'winter. stay warm out there',
      },
      sky: {
        clear: ['{temp} and clear{where}. nice day', 'clear skies. good sign'],
        cloudy: ['overcast{where}. focus weather'],
        fog: ['foggy out{where}. stay in, code'],
        drizzle: ['drizzling{where}. fine by me'],
        rain: ['raining{where}. perfect excuse to stay in', 'rain on the window. good soundtrack'],
        snow: ['snow{where}. huh. nice', "snowing. don't go out there"],
        storm: ['storm rolling in{where}. save your work. now'],
      },
    },
    status: {
      calm: 'Kai · chilling',
      watching: "Kai · I'm listening",
      working: 'Kai · locked in',
      win: 'Kai · called it ✦',
      loss: "Kai · it's not winning",
      rest: 'Kai · coffee break ☕',
      away: 'Kai · not missing you. at all',
      sleep: 'Kai · resting his eyes',
    },
  },
  bond: {
    moments: [
      {
        title: 'a moment with Kai',
        lines: [
          "worked night shifts at a café once.",
          "you learn pretty fast who panics when things go sideways and who actually fixes things.",
          "haven't decided which one you are yet.",
        ],
      },
      {
        title: 'a moment with Kai',
        lines: [
          "I skate. badly. there, I said it.",
          "spent a whole summer skating until I could land one stupid trick. fell maybe four hundred times.",
          "you have that same annoying refusal to leave things broken. not bad.",
        ],
      },
      {
        title: 'a moment with Kai',
        lines: [
          "I keep a notebook of things worth remembering.",
          "tricks people taught me. mistakes I don't want twice. good ideas.",
          "you've made the book three times now. don't get smug.",
        ],
      },
      {
        title: 'a moment with Kai',
        lines: [
          "you're terrible at stopping when you're onto something.",
          "I know because I do the exact same thing.",
          "so when I tell you to take five, that's not advice. it's mutual enforcement.",
        ],
      },
      {
        title: 'a moment with Kai',
        lines: [
          "I thought I'd get bored once I figured out how you work.",
          "turns out you keep surprising me. irritating habit.",
          "…I'm glad it's you, partner.",
        ],
      },
      {
        title: 'a moment with Kai',
        lines: [
          "I almost quit doing this once. burned myself out trying to be the best at everything.",
          "took me a while to learn that good work doesn't have to be lonely work.",
          "you're pretty solid evidence.",
        ],
      },
      {
        title: 'a moment with Kai',
        lines: [
          "one day I want a tiny café. night hours. good coffee, a counter for laptops.",
          "a rail out back for skating. a rule: everyone takes breaks. strictly enforced.",
          "you'd get a stool with your name on it. apparently you'd just show up anyway.",
        ],
      },
      {
        title: 'a moment with Kai',
        lines: [
          "got a new deck. painted the bottom myself. took three weekends.",
          "it's covered in little bugs, squashed flat. one for every bug we fixed together.",
          "so it's ours. …at least the idea is. the deck's mine. hands off ✦",
        ],
      },
      {
        title: 'a moment with Kai',
        lines: [
          "rough day. the café where I worked nights closed. for good.",
          "I wanted to sulk. came and sat here instead.",
          "figured you'd be here. …good call, apparently.",
        ],
      },
      {
        title: 'a moment with Kai',
        lines: [
          "every heart's gold. yeah, I noticed.",
          "you're good. I'm good. somehow we're even better together.",
          "partner in crime. officially. no take-backs ✦",
        ],
      },
    ],
    title: 'partner in crime',
    warm: [
      "hey. …good to see you. don't make it weird",
      "there's my favorite teammate. …you didn't hear that",
      "alright, you're here. now we can actually win",
    ],
    favorites: [
      { kind: 'morning', name: 'early starts', line: "early start. respect. that was my old shift" },
      { kind: 'weekend', name: 'weekend grinds', line: 'weekend session. show-off. …I like it' },
    ],
    hiBack: [
      'hey yourself. what do you want?',
      'hi. …what? I can say hi',
      'yo. took you long enough',
      { text: "hey. glad you stopped by. don't tell anyone I said that", hearts: 3 },
    ],
  },
  story: {
    name: 'learning the guitar',
    beats: [
      { after: 3, line: 'bought a used guitar. three strings are fine. the other three are a problem' },
      { after: 8, line: "my fingertips hurt. apparently that's the point. great" },
      { after: 15, line: "learned three chords. can't switch between them yet. so it's one chord, very confidently" },
      { after: 25, line: "neighbor knocked on the wall last night. I'm counting that as an encore" },
      { after: 40, line: 'chord changes are clean now. mostly. the neighbor stopped knocking' },
      { after: 60, line: "broke a string mid-song. nearly quit. didn't. restrung it. growth" },
      { after: 90, line: 'played a whole song start to finish. nobody heard. good. …it was decent' },
      { after: 130, line: "learned a song. for you. it's short and I messed up one chord. don't clap. …okay, you can clap ✦" },
    ],
  },
  look: {
    theme: 0xf0a35e,
    palette: {
      hair: 0x2c3448,
      hairShade: 0x1b2131,
      hairShine: 0x56627e,
      skin: 0xf2d2b6,
      skinShade: 0xdcb196,
      eyes: 0xd08a2e,
      eyesDark: 0x5a3410,
      eyesGlow: 0xf0c27a,
      blush: 0xeaa391,
      lips: 0x9e5a4f,
      top: 0x3f5a52,
      topShade: 0x2b403a,
      inner: 0xeef0f2,
      innerShade: 0xc3c8cf,
      accent: 0xd9dde3,
      detail: 0x7d6a5c,
    },
    hair: 'short',
    bangs: 'swept',
    ahoge: true,
    face: 'square',
    brows: 'thick',
    lashes: false,
    facialHair: 'none',
    outfit: 'jacket',
    glasses: false,
    accessories: [],
  },
  // Sassy: a hand to his chin, smug, a fist pump now and then; never a big cheer
  moods: {
    // A win: smug for a beat, then a fist punched up in the air, with a hop: called it
    celebrate: {
      eyes: 'lidded',
      mouth: 'smirk',
      arms: 'chin',
      blush: false,
      hop: false,
      frames: [{}, { arms: 'pump', eyes: 'happy', mouth: 'grin', hop: 1 }, { arms: 'pump', eyes: 'happy', mouth: 'grin' }, { arms: 'pump', eyes: 'happy', mouth: 'grin', hop: 1 }],
      every: 3,
    },
    happy: { mouth: 'smirk', arms: 'chin', blush: false },
    // A loss: jaw set, fist up, ready to go again
    comfort: { eyes: 'determined', mouth: 'frown', arms: 'fist', tear: false },
    worried: { eyes: 'determined', mouth: 'frown', arms: 'fist', sweat: false },
    watching: { mouth: 'smirk', blush: false },
    thinking: { arms: 'chin' },
    // Missing you, not that he'd say so: hand to chin, a wave now and then
    miss: {
      eyes: 'lidded',
      arms: 'chin',
      blush: false,
      frames: [...Array.from({ length: 12 }, () => ({})), { arms: 'wave', eyes: 'soft' }, { arms: 'waveB', eyes: 'soft' }, { arms: 'wave', eyes: 'soft' }, { arms: 'waveB', eyes: 'soft' }],
      every: 2,
    },

  },
}
