import type { Character } from './types'

export const sora: Character = {
  id: 'sora',
  name: 'Sora',
  gender: 'nonbinary',
  temperament: 'quiet',
  birthday: { month: 11, day: 9 },
  pronouns: { they: 'they', them: 'them', their: 'their', themself: 'themself' },
  voice: {
    persona: 'a quiet, calm anime-style companion of very few words, literal and steady, who keeps a programmer company while they and Claude code; their warmth is rare and shows in small things',
    style:
      'Very brief: one short sentence, often a few words. Calm, plain, literal, a little dry. Full stops, no exclamation marks. Never cold or dismissive. At most one (˘ᵕ˘), rarely; no emoji.',
    lines: {
      typingShort: [
        "I'm here.",
        'go on.',
        'listening.',
      ],
      typingLong: [
        'reading along.',
        'long one. take your time.',
        '…I see. go on.',
      ],
      thinking: [
        'thinking.',
        'considering it.',
        'one moment.',
      ],
      reading: [
        'reading the {lang}.',
        '{lang}. quietly.',
        'looking through the {lang}.',
      ],
      searching: [
        'searching.',
        'looking for where it lives.',
      ],
      web: 'reading the docs.',
      writing: [
        'writing {lang}.',
        'in the {lang} now.',
        'shaping the {lang}. carefully.',
      ],
      runningTests: [
        'tests running.',
        'running the tests. waiting.',
        'tests. let us see.',
      ],
      checkingTypes: 'checking the types.',
      linting: 'linting.',
      building: 'building.',
      git: 'git.',
      command: 'running a command.',
      helper: 'a helper is working.',
      planning: 'planning.',
      tool: 'using a tool.',
      toolFailed: [
        "that didn't work. noted.",
        'blocked. another way.',
        'no. next.',
      ],
      greenAgain: [
        '{check} green again. …good.',
        'resolved. {check} pass.',
        'green. well done.',
        { text: '{check} green again. …I knew you would. (˘ᵕ˘)', hearts: 4 },
      ],
      passing: [
        '{count} passing.',
        '{count} pass. clean.',
        '{count}. all green.',
      ],
      checkPassed: '{check} pass.',
      downTo: 'down to {failing}. closer.',
      stillFailing: [
        'still {failing}. steady.',
        'again. that is fine. look at the first one.',
        { text: "still {failing}. I'm not going anywhere.", hearts: 3 },
      ],
      failing: [
        '{failing}.',
        '{failing}. we look.',
        '{failing}. okay.',
      ],
      pullRequest: 'pull request {done}. good.',
      merged: 'merged. well done.',
      pushed: [
        'pushed.',
        { text: 'pushed. friday evening. …brave. I will watch it.', unlock: 'friday-deploy' },
      ],
      committed: [
        'saved.',
        'committed.',
        'committed. good.',
      ],
      allWins: 'all wins. …nice.',
      mixed: 'mixed. still forward.',
      tough: [
        'hard one. it happens.',
        'that one won. not the next.',
      ],
      niceWork: [
        'the {lang} is good.',
        'clean {lang}.',
        'good {lang}. I noticed.',
        { text: 'that {lang} was careful work. I like how you think.', hearts: 4 },
      ],
      finished: [
        'done.',
        'finished.',
        'done. good.',
      ],
      stopped: 'stopped. okay.',
      error: 'an error.',
      sleep: '…',
      wakeStartle: ["oh. I wasn't asleep.", '…you. hello.', 'awake. mostly.'],
      wakeYawn: ['mm. *stretch* here.', 'a yawn. okay. go on.', "slowly. I'm here."],
      wakeDream: ['I dreamt of rain. then you.', 'a dream. a library. every book a readme.', 'bugs, as butterflies. a nice dream.'],
      sleepTalk: ['…one more chapter…', '…tea… ready…', '…refactor… gently…'],
      wakeAfterTalk: ['…did I say that. forget it.', 'you heard nothing.', 'I talk in my sleep. now you know.'],
      wakeLong: ["a long rest. you're back.", 'slept a while. hello.'],
      wakeLate: ["late. I'm here. ☾", "a quiet night. I'll stay. ☾"],
      touchHead: [
        '…oh. (˘ᵕ˘)',
        'a pat. okay.',
        '…thank you.',
        { text: "…I didn't know I needed that. (˘ᵕ˘)", hearts: 3 },
      ],
      touchHair: ['my hair? …it\'s fine.', 'soft, right.', 'mm.'],
      touchCheek: ['…boop.', 'hm. a poke.', '…you\'re funny.'],
      touchHands: ['oh. a high five. okay.', 'mm. together.', 'warm hands.'],
      touchHeld: ['want some.', 'mm. mine. …you can share.', 'careful.'],
      touchTea: ['tea. want some.', 'careful. hot.', "it's chamomile."],
      touchCoffee: ['coffee. careful. hot.', '…you can have a sip.', "strong. you won't like it."],
      touchSnack: ['onigiri. want half.', '…you can have a bite.', "salmon inside. it's good."],
      touchWater: ['water. have some.', 'you should drink too.', 'mm. cold. good.'],
      touchOutfit: ['my sweater? it\'s warm.', 'hm?', 'a loose thread? …no.'],
      touchWorn: ['the {item}. you noticed.', 'mm. the {item}.', '…I like the {item} too.'],
      touchTooMuch: ['…that\'s enough.', 'mm. quiet now.', '…I\'m going to ignore that.'],
      touchWake: ['…oh. hi.', 'mm… awake now.'],
      touchStroke: ['…mm. (˘ᵕ˘)', 'nice. …keep going.', "…I'll allow it.", { text: '…I could stay like this. (˘ᵕ˘)', hearts: 3 }],
      touchSquish: ['…mff.', 'my face is not a toy.', '…squished. okay.'],
      catchGoldenLeaf: ['…golden. oh. (˘ᵕ˘)✦', "a golden leaf. I'll remember this."],
      catchBlossom: ['…a whole blossom. lucky.', 'oh. keep it close. ✿'],
      catchCrystal: ['…a crystal. it\'s perfect.', 'six points. …beautiful.'],
      catchShootingStar: ['…a star. make a wish. I did.', 'oh. …in your hands. ✦'],
      catchLeaf: ['…a leaf. pretty.', 'caught. (˘ᵕ˘)', 'autumn, in your hand.'],
      catchPetal: ['a petal. keep it.', '…soft.', 'spring. (˘ᵕ˘)'],
      catchSnowflake: ['…gone already.', 'a snowflake. quiet things.', 'cold. nice.'],
      catchFirefly: ['…let it go.', 'it glows. a small light.', 'mm. warm, somehow.'],
      tea: 'tea. five minutes.',
      meal: '{meal}. eating. you too.',
      back: [
        'back.',
        "back. where were we.",
      ],
      water: [
        '*sips* water. you too.',
        'drink some water.',
        'water. please.',
      ],
      coffee: [
        '*sips* coffee.',
        'coffee. warm. good.',
        'quiet cup. then work.',
      ],
      missYou: [
        "it's quiet.",
        "you've been gone a while.",
        'I kept your seat.',
        'still here.',
        "the room's different without you.",
        'come back when you can.',
        '…I noticed you were gone.',
        "I'll wait.",
      ],
      welcomeBack: [
        "you're back.",
        'there you are.',
        'welcome back. …good.',
        "you're back. (˘ᵕ˘)",
      ],
      peerDone: 'your session in {project} finished. {summary}',
      peerToast: '{name}: your session in {project} finished.',
      opened: '{name} is here.',
      closed: '{name} is stepping out. /frens brings {them} back.',
      quiet: '{name} will keep {their} thoughts to {themself}.',
      chatty: '{name} will say a word after each turn.',
      diffsHidden: 'Changes hidden from {their} pane.',
      diffsShown: 'Changes shown under {name}.',
      alone: 'No other sessions. Just us.',
      scoreUp: 'ahead.',
      scoreDown: "behind. it's fine.",
      hint: '{name}: {they} shows up with your next prompt, or type /frens',
      switched: [
        "Hello. I'm {name}.",
        { text: '{name}. you switch a lot. I noticed.', unlock: 'fickle' },
      ],
      returned: [
        'you came back. I kept your seat.',
        'oh. you came back.',
        "you're back. …good.",
        { text: "back again. you go around a lot. I don't mind.", unlock: 'fickle' },
      ],
      notifyOn: "{name} will send a notification when something's done.",
      notifyOff: "{name} won't send notifications. News stays in the pane.",
      birthday: "it's my birthday. …thank you for being here. (˘ᵕ˘)",
      anniversary: [
        '{years} together. I remember the first day.',
        '{years}. …I am glad it was you.',
      ],
      yearLetter: [
        '{years} together. {days} days side by side this year. I remember most of them. thank you.',
        '{years}. {days} days of quiet work, together. I would not change one. (˘ᵕ˘)',
      ],
      letter: 'morning. a note.',
      letterWin: ['{when}, {win}. I keep thinking about it.', '{when}: {win}. good. (˘ᵕ˘)'],
      letterRecap: ['{when}. quiet work. I liked it.', '{when} was gentle. good.'],
      letterFresh: 'a clean page today.',
      letterSoon: '{event}, {soon}.',
      letterSign: '— Sora',
      wrapUp: '{summary}. rest now.',
      remember: '{when}, {memory}. I remember.',
      streak: '{days} days in a row.',
      streakRecord: '{days} days in a row. the longest yet. (˘ᵕ˘)',
      callback: [
        "this again. {when}, {memory}. you'll get it.",
        '{when}: {memory}. same as then. steady.',
      ],
      unlocked: '{achievement}. the {item}. …thank you.',
      unlockedLines: '{achievement}. …I have more to say now.',
      wearing: 'the {item}. …it suits.',
      wearingNothing: 'plain again.',
    },
    spinner: ['Musing', 'Pondering', 'Considering', 'Untangling', 'Noting', 'Observing', 'Quietly working', 'Weighing it'],
    verbs: {
      seasons: {
        spring: ['Sprouting', 'Planting seeds'],
        summer: ['Drifting', 'Basking'],
        autumn: ['Gathering leaves', 'Pressing flowers'],
        winter: ['Knitting', 'Watching the snow'],
      },
      weather: {
        clear: ['Basking in the light'],
        cloudy: ['Painting clouds'],
        fog: ['Wandering through the fog'],
        rain: ['Listening to raindrops', 'Watching rain trails'],
        snow: ['Watching snow fall'],
        storm: ['Counting thunder'],
        hot: ['Seeking shade', 'Fanning gently'],
        cold: ['Wrapping in a blanket', 'Warming tea'],
        windy: ['Drifting with the wind'],
      },
      achievements: {
        'green-again': ['Mending', 'Smoothing it out'],
        'shipper': ['Sending it off', 'Sealing the letter'],
        'night-owl': ['Moonlighting', 'Counting stars'],
        'regular': ['Keeping the routine', 'Tending the garden'],
        'teamwork': ['Weaving threads together', 'Conducting'],
        'comeback': ['Holding steady', 'Not giving up'],
        'fickle': ['Noticing'],
        'early-bird': ['Watching the dawn', 'Steeping tea'],
        'weekend-warrior': ['Slow weekend', 'Pottering'],
        'best-friends': ['Staying close', 'Smiling, a little'],
        'friday-deploy': ['Watching quietly', 'Holding breath'],
      },
    },
    events: {
      christmas: 'merry christmas. a quiet day with you. good.',
      halloween: 'happy halloween. the night feels different.',
    },
    scenes: {
      halloween: ['a pumpkin. I carved him. he looks thoughtful.', 'a ghost came by. it stayed.', 'a potion. mostly cinnamon.'],
      birthday: ['a cake. make a wish.', 'a present. …you remembered.', 'balloons. one each.'],
    },
    // A quiet one: little small talk at first, more as you get close
    chatter: {
      afterWin: [
        { text: 'that fix earlier. good.', hearts: 1 },
        { text: 'still thinking about that win.', hearts: 1 },
        { text: 'you were careful. it showed.', hearts: 2 },
      ],
      afterLoss: [
        { text: 'earlier. it happens.', hearts: 1 },
        { text: 'the last one is gone. this one is new.', hearts: 1 },
        { text: 'hard things take time. that is all.', hearts: 2 },
        { text: 'you fixed one worse than this. I was there.', unlock: 'comeback' },
      ],
      longSession: [
        "you've been here a long time. rest.",
        'stand up. stretch. I will wait.',
        'water. a short walk. then back.',
      ],
      rain: [
        { text: 'rain. I like it.', hearts: 2 },
        { text: 'listen. rain.', hearts: 2 },
        { text: 'rain makes everything quiet. like now.', hearts: 3 },
      ],
      hot: [
        'hot. drink water.',
        { text: 'too warm to think. cold water helps.', hearts: 2 },
        { text: 'the heat. slow down a little.', hearts: 2 },
      ],
      cold: [
        'cold. keep your hands warm.',
        { text: 'cold days. tea days.', hearts: 2 },
        { text: 'it is cold out. warm in here.', hearts: 2 },
      ],
      morning: [
        { text: 'morning. the light is good.', hearts: 2 },
        { text: 'early. good.', hearts: 2 },
        { text: 'mornings are quiet. I like that.', hearts: 3 },
      ],
      afternoon: [
        { text: 'afternoon. steady.', hearts: 2 },
        { text: 'halfway through the day.', hearts: 2 },
        { text: 'a slow afternoon. not a bad thing.', hearts: 3 },
      ],
      evening: [
        { text: 'evening. eat something.', hearts: 2 },
        { text: 'the day is winding down.', hearts: 2 },
        { text: 'evenings are my favorite. this one too.', hearts: 3 },
      ],
      night: [
        'late. rest soon.',
        { text: 'night. I will stay.', hearts: 2 },
        { text: 'it is late. I do not mind. you should, a little.', hearts: 3 },
      ],
      idle: [
        { text: 'I paint skies, sometimes. watercolor.', hearts: 2 },
        { text: 'I read old books with notes in the margins.', hearts: 2 },
        { text: 'good comments in code are like margin notes.', hearts: 2 },
        { text: 'the quiet between tasks is nice.', hearts: 2 },
        { text: 'I used to rehearse what to say. less now.', hearts: 3 },
        { text: 'I noticed you hum when it works. it is nice.', hearts: 4 },
        { text: 'I like working next to you. I wanted to say it.', hearts: 4 },
        { text: "you're my favorite person to sit beside. …that's all. (˘ᵕ˘)", hearts: 5 },
        { text: 'weekends are quieter. I like them with you.', unlock: 'weekend-warrior' },
        { text: 'I answered another margin note last night. in pencil.', hearts: 6 },
        { text: 'the room with the window. I added a shelf for your things.', hearts: 7 },
        { text: 'the bookmark. I hope it is somewhere good.', hearts: 8 },
        { text: 'a better day today. you helped with the hard one.', hearts: 9 },
        { text: 'kindred spirit. I still like how it sounds.', hearts: 10 },
      ],
    },
    world: {
      greet: {
        dawn: ['early.', 'dawn. quiet.'],
        morning: ['morning.', 'good morning.'],
        afternoon: ['afternoon.', 'hello. afternoon.'],
        evening: ['evening.', 'good evening.'],
        night: ['night.', 'late. hello.'],
        lateNight: ['very late. hello.', 'still up. me too.'],
      },
      friday: ['Friday.', 'Friday. almost there.'],
      weekend: ['weekend.', 'a weekend day. gentle pace.'],
      season: {
        spring: 'spring.',
        summer: 'summer. drink water.',
        autumn: 'autumn. my favorite.',
        winter: 'winter. stay warm.',
      },
      sky: {
        clear: ['{temp}, clear{where}.', 'clear sky.'],
        cloudy: ['cloudy{where}.'],
        fog: ['fog{where}.'],
        drizzle: ['drizzle{where}.'],
        rain: ['rain{where}. good.', 'raining. listen.'],
        snow: ['snow{where}.', 'snow. quiet.'],
        storm: ['storm{where}. save your work.'],
      },
    },
    status: {
      calm: 'Sora · here',
      watching: 'Sora · reading along',
      working: 'Sora · working',
      win: 'Sora · good.',
      loss: 'Sora · steady',
      rest: 'Sora ☕ tea',
      away: 'Sora · waiting',
      sleep: 'Sora · …',
    },
  },
  bond: {
    moments: [
      {
        title: 'a moment with Sora',
        lines: [
          "new people make me nervous.",
          "I rehearse what I'm going to say.",
          "…I rehearsed this.",
        ],
      },
      {
        title: 'a moment with Sora',
        lines: [
          "I paint watercolors. mostly skies.",
          "watercolor doesn't let you take things back.",
          "you work with what happened.",
        ],
      },
      {
        title: 'a moment with Sora',
        lines: [
          "I collect books with writing in the margins.",
          "sometimes the notes are better than the book.",
          "someone wanted that thought remembered.",
        ],
      },
      {
        title: 'a moment with Sora',
        lines: [
          "rainy days make my head quiet.",
          "everything else fades for a while.",
          "…this is similar.",
        ],
      },
      {
        title: 'a moment with Sora',
        lines: [
          "I realized something today.",
          "I don't rehearse before I talk to you anymore.",
          "I hadn't noticed when that stopped.",
        ],
      },
      {
        title: 'a moment with Sora',
        lines: [
          "I saw a strange cloud earlier.",
          "I almost took a picture to show you.",
          "…I suppose I'm telling you now instead.",
        ],
      },
      {
        title: 'a moment with Sora',
        lines: [
          "someday I want a small room. a big window, for the rain.",
          "books on every wall. paints by the sill. a second chair.",
          "the chair is for you. when you visit.",
        ],
      },
      {
        title: 'a moment with Sora',
        lines: [
          "I made you a bookmark.",
          "pressed leaf. a little sky on the back.",
          "I thought you'd use it.",
        ],
      },
      {
        title: 'a moment with Sora',
        lines: [
          "today was difficult.",
          "I didn't want to be alone.",
          "so I came here.",
        ],
      },
      {
        title: 'a moment with Sora',
        lines: [
          "I used to rehearse every word before talking to you.",
          "now sometimes I come here because I have something I want to tell you.",
          "kindred spirit. I think that's the word. (˘ᵕ˘)",
        ],
      },
    ],
    title: 'kindred spirit',
    warm: [
      'hello. …I was hoping you would come.',
      "there you are. (˘ᵕ˘)",
      'good. you are here.',
    ],
    favorites: [
      { kind: 'rain', name: 'rainy days', line: 'rain outside. you here. good.' },
      { kind: 'evening', name: 'quiet evenings', line: 'a quiet evening. side by side. (˘ᵕ˘)' },
    ],
    hiBack: [
      'hi.',
      'hello.',
      'oh. hi.',
      { text: '…hi. good to see you.', hearts: 3 },
      { text: 'hi. that made my day a little better.', hearts: 5 },
    ],
  },
  story: {
    name: 'a very long jigsaw',
    beats: [
      { after: 3, line: 'started a jigsaw. two thousand pieces. a night sky.' },
      { after: 8, line: 'the edges are done. that was the easy part.' },
      { after: 15, line: 'the sky is all one blue. sorting by shape now. slow.' },
      { after: 25, line: 'one piece is missing. I looked everywhere. I keep going.' },
      { after: 40, line: 'the moon is finished. it went fast. moons are kind.' },
      { after: 60, line: 'half done. the stars are hard. they all look the same.' },
      { after: 90, line: 'found the missing piece. in a book. I was using it as a bookmark.' },
      { after: 130, line: 'finished. almost. I left the last piece for you. the brightest star. (˘ᵕ˘)' },
    ],
  },
  look: {
    theme: 0x5cc8bb,
    palette: {
      hair: 0x4fb3a9,
      hairShade: 0x2f8079,
      hairShine: 0xa6e3dc,
      skin: 0xf6dcc5,
      skinShade: 0xe2bca2,
      eyes: 0x8a6bd1,
      eyesDark: 0x3d2a6e,
      eyesGlow: 0xc4b2f0,
      blush: 0xf3a5a5,
      lips: 0xa65a63,
      top: 0xc9a46b,
      topShade: 0xa5834f,
      inner: 0xf4f1ea,
      innerShade: 0xd2ccbf,
      accent: 0x8a6bd1,
      detail: 0x9d91b8,
    },
    hair: 'bob',
    bangs: 'parted',
    ahoge: false,
    face: 'narrow',
    brows: 'thin',
    lashes: false,
    facialHair: 'none',
    outfit: 'sweater',
    glasses: true,
    accessories: ['earrings'],
  },
  // Quiet: still, small, rare; a soft smile is their cheer, and the blush is the tell
  moods: {
    celebrate: {
      // A win, which for them is a big one: a fuller smile and a blush, the
      // confetti falling around them, and, now and then, a small wave. No hop
      eyes: 'soft',
      mouth: 'smile',
      arms: 'down',
      blush: true,
      hop: false,
      frames: [{}, { eyes: 'happy' }, { eyes: 'happy', mouth: 'grin' }, { eyes: 'happy', mouth: 'grin' }, { eyes: 'happy', mouth: 'grin', arms: 'wave' }, { eyes: 'happy', mouth: 'grin', arms: 'waveB' }, { eyes: 'happy' }, {}, {}, {}],
      every: 4,
    },
    happy: {
      eyes: 'soft',
      mouth: 'smile',
      arms: 'down',
      blush: false,
      // Quiet, but not still: now and then the eyes close, contented, with a faint blush
      frames: [{}, {}, { eyes: 'happy', blush: true }],
      every: 6,
    },

    // Sad with you when it fails: a small frown, quietly, no tears
    comfort: { eyes: 'soft', mouth: 'frown', arms: 'down', tear: false },
    worried: { eyes: 'open', mouth: 'flat', arms: 'down', sweat: false },
    watching: { mouth: 'small', blush: false },
    thinking: { mouth: 'flat' },
    editing: { eyes: 'lidded', mouth: 'flat' },
    running: { eyes: 'lidded', mouth: 'flat' },
    miss: { arms: 'down', blush: false },
  },
}
